### PR TITLE
T10F22-36  Profile Fix Bugs

### PR DESCRIPTION
**Pull request by Zevez7**

### CODE REVIEW

**Review by hzhou74 — APPROVED** [review]
what bug does it cause? Anyway good work

**Review by ujjvalksharma — CHANGES_REQUESTED** [review]
Please change the PR name as I cannot identify the Jira ticket name

**Comment by Zevez7** [comment]
There's no jira ticket, this is some small bug that I'm fixing. I don't think we need to create jira tickets for small bugs.

**Comment by ujjvalksharma** [comment]
Your title 'fixed small bug on editprofile and profile/index ' is not descriptive enough for other teammates to know what the bug is all about and how it is fixed. Jira ticket are always effective way to communicate what you are trying to fix.

**Comment by Zevez7** [comment]
Ok, I made a ticket

**Pull request merged**
