### PR TITLE
T10 f22 43 reorder react folder excluding svg folder for space

### PR DESCRIPTION
**Pull request by Zevez7**
move all the files from tuiter folder into main tuiter-project-react folder and also delete most of svg files we did not use to reduce 12 mb of un used svg from frontawesome.
Deloyment was successful please check the deployment web 
https://visionary-snickerdoodle-62d498.netlify.app/

### CODE REVIEW

**Review by hzhou74 — COMMENTED** [review]
reviewd

**Comment by thematthewchan** [comment]
looks good to me

**Review by hzhou74 — APPROVED** [review]
Look great.After optimizing the code it will run smoother

**Review by thematthewchan — APPROVED** [review]
the changes of removing the unnecessary files to reduce the file sizes look good to me

**Pull request merged**
